let adminOrders=[],deliveryUsers=[],adminProducts=[],team=[]; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function guard(){const m=await JN.api('/api/me');if(!m.user||m.user.role!=='ADMIN')location.href='/login.html';else{$('#staffName').textContent=m.user.name;await refreshAll();}}
async function refreshAll(){await Promise.all([loadDash(),loadOrders(),loadProducts(),loadTeam()]);}
async function loadDash(){const d=await JN.api('/api/admin/dashboard');$('#statOrders').textContent=d.stats.todayOrders;$('#statRevenue').textContent=JN.money(d.stats.revenue);$('#statPending').textContent=d.stats.pending;$('#statStock').textContent=d.stats.lowStock;const ent=Object.entries(d.blocks).sort((a,b)=>b[1]-a[1]);$('#blockLoad').innerHTML=ent.map(([k,v])=>`<div class="bar-row"><span>${JN.esc(k)}</span><div><i style="width:${Math.min(100,v*14)}%"></i></div><b>${v}</b></div>`).join('')||'<div class="empty slim">No active block deliveries.</div>';$('#audit').innerHTML=d.audit.map(a=>`<div class="audit-item"><b>${JN.esc(a.action)}</b><span>${JN.esc(a.actor)} · ${new Date(a.at).toLocaleString()}</span><small>${JN.esc(a.detail)}</small></div>`).join('');}
async function loadOrders(){const d=await JN.api('/api/admin/orders');adminOrders=d.orders;deliveryUsers=d.deliveryUsers;renderOrders();}
function renderOrders(){const q=$('#orderSearch').value.toLowerCase(),f=$('#statusFilter').value;const arr=adminOrders.filter(o=>(!f||o.status===f)&&(!q||`${o.id} ${o.name} ${o.rollNumber||''} ${o.customerType||'STUDENT'} ${o.block} ${o.className}`.toLowerCase().includes(q)));$('#ordersTable').innerHTML=arr.map(o=>`<tr><td><b>${o.id}</b><small>${new Date(o.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></td><td><b>${JN.esc(o.name)}</b><span class="type-badge ${(o.customerType||'STUDENT').toLowerCase()}">${o.customerType==='TEACHER'?'Teacher':'Student'}</span><small>${o.customerType==='TEACHER'?'No roll number':JN.esc(o.rollNumber||'')}</small></td><td>${JN.esc(o.className)}<small>${JN.esc(o.block)} · ${JN.esc(o.classNumber)}</small></td><td>${o.items.map(i=>`${i.emoji} ${JN.esc(i.name)} ×${i.qty}`).join('<br>')}</td><td><b>${JN.money(o.total)}</b><small>${JN.esc(o.paymentMethod)}</small></td><td><select data-assign="${o.id}"><option value="">Unassigned</option>${deliveryUsers.map(u=>`<option value="${u.id}" ${o.assignedTo===u.id?'selected':''}>${JN.esc(u.name)}</option>`).join('')}</select></td><td><select data-status="${o.id}">${['PLACED','ACCEPTED','PREPARING','READY','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty slim">No orders.</div></td></tr>';$$('[data-assign]').forEach(x=>x.onchange=()=>patchOrder(x.dataset.assign,{assignedTo:x.value||null}));$$('[data-status]').forEach(x=>x.onchange=()=>patchOrder(x.dataset.status,{status:x.value}));}
async function patchOrder(id,b){try{await JN.api('/api/admin/orders/'+id,{method:'PATCH',body:JSON.stringify(b)});JN.toast('Order updated');await Promise.all([loadOrders(),loadDash()]);}catch(e){JN.toast(e.message,'bad')}}
async function loadProducts(){adminProducts=(await JN.api('/api/admin/products')).products;$('#productRows').innerHTML=adminProducts.map(p=>`<tr><td><span class="tiny-emoji">${p.emoji}</span><b>${JN.esc(p.name)}</b><small>${JN.esc(p.category)}</small></td><td><input class="table-input" type="number" value="${p.price}" data-field="price" data-pid="${p.id}"></td><td><input class="table-input" type="number" value="${p.discount||0}" data-field="discount" data-pid="${p.id}"></td><td><input class="table-input ${p.stock<=10?'low':''}" type="number" value="${p.stock}" data-field="stock" data-pid="${p.id}"></td><td><label class="switch"><input type="checkbox" ${p.active!==false?'checked':''} data-field="active" data-pid="${p.id}"><span></span></label></td></tr>`).join('');$$('[data-pid]').forEach(x=>x.onchange=()=>patchProduct(x.dataset.pid,{[x.dataset.field]:x.type==='checkbox'?x.checked:Number(x.value)}));}
async function patchProduct(id,b){try{await JN.api('/api/admin/products/'+id,{method:'PATCH',body:JSON.stringify(b)});JN.toast('Product updated');await Promise.all([loadProducts(),loadDash()]);}catch(e){JN.toast(e.message,'bad')}}
async function addProduct(e){e.preventDefault();const b=Object.fromEntries(new FormData(e.target).entries());b.featured=!!b.featured;try{await JN.api('/api/admin/products',{method:'POST',body:JSON.stringify(b)});e.target.reset();$('#productModal').close();JN.toast('Product added');loadProducts();}catch(er){JN.toast(er.message,'bad')}}
async function loadTeam(){team=(await JN.api('/api/admin/users')).users;$('#teamGrid').innerHTML=team.map(u=>`<article class="team-card"><div class="avatar">${u.role==='DELIVERY'?'🛵':'👨‍🍳'}</div><div><b>${JN.esc(u.name)}</b><span>${JN.esc(u.username)} · ${u.role}</span></div><label class="switch"><input type="checkbox" ${u.active?'checked':''} data-useractive="${u.id}"><span></span></label></article>`).join('');$$('[data-useractive]').forEach(x=>x.onchange=async()=>{await JN.api('/api/admin/users/'+x.dataset.useractive,{method:'PATCH',body:JSON.stringify({active:x.checked})});JN.toast('Account updated');});}
async function addUser(e){e.preventDefault();try{await JN.api('/api/admin/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target).entries()))});e.target.reset();$('#userModal').close();JN.toast('Staff account created');await Promise.all([loadTeam(),loadOrders()]);}catch(er){JN.toast(er.message,'bad')}}
function tab(name){$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==name);}
document.addEventListener('DOMContentLoaded',()=>{$$('[data-tab]').forEach(x=>x.onclick=()=>tab(x.dataset.tab));$('#orderSearch').oninput=renderOrders;$('#statusFilter').onchange=renderOrders;$('#addProductBtn').onclick=()=>$('#productModal').showModal();$('#addUserBtn').onclick=()=>$('#userModal').showModal();$('#productForm').onsubmit=addProduct;$('#userForm').onsubmit=addUser;$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());guard();setInterval(()=>{loadDash();loadOrders()},15000);});
