let products=[],cart=JSON.parse(localStorage.getItem('jn-cart')||'[]'),favorites=new Set(JSON.parse(localStorage.getItem('jn-favs')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function saveCart(){localStorage.setItem('jn-cart',JSON.stringify(cart));renderCart();}
function discounted(p){return Math.round(p.price*(1-(p.discount||0)/100));}
async function loadProducts(){try{products=(await JN.api('/api/products')).products;renderCategories();renderProducts();renderCart();}catch(e){JN.toast(e.message,'bad')}}
function renderCategories(){const cats=['All',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=cats.map((c,i)=>`<button class="chip ${i===0?'active':''}" data-cat="${JN.esc(c)}">${JN.esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{$$('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts();});}
function renderProducts(){const q=$('#search').value.trim().toLowerCase();const cat=$('[data-cat].active')?.dataset.cat||'All';const list=products.filter(p=>(cat==='All'||p.category===cat)&&(!q||`${p.name} ${p.category} ${p.ingredients?.join(' ')}`.toLowerCase().includes(q)));$('#productGrid').innerHTML=list.map(p=>`<article class="product-card reveal"><div class="product-art art-${p.category.toLowerCase().replace(/\W/g,'')}"><span>${p.emoji}</span>${p.discount?`<b class="discount">-${p.discount}%</b>`:''}<button class="heart ${favorites.has(p.id)?'active':''}" data-fav="${p.id}" aria-label="Favourite">♥</button></div><div class="product-body"><div class="eyebrow">${JN.esc(p.category)} · ${p.calories||'—'} kcal</div><h3>${JN.esc(p.name)}</h3><p>${JN.esc(p.description)}</p><div class="ingredients">${(p.ingredients||[]).slice(0,4).map(x=>`<span>${JN.esc(x)}</span>`).join('')}</div><div class="product-foot"><div><strong>${JN.money(discounted(p))}</strong>${p.discount?`<s>${JN.money(p.price)}</s>`:''}<small>${p.stock} left</small></div><button class="btn mini" data-custom="${p.id}" ${p.stock<1?'disabled':''}>Customize +</button></div></div></article>`).join('')||'<div class="empty">No drinks match your search.</div>';
$$('[data-fav]').forEach(b=>b.onclick=()=>{favorites.has(b.dataset.fav)?favorites.delete(b.dataset.fav):favorites.add(b.dataset.fav);localStorage.setItem('jn-favs',JSON.stringify([...favorites]));renderProducts()});$$('[data-custom]').forEach(b=>b.onclick=()=>openCustomize(b.dataset.custom));}
function openCustomize(id){const p=products.find(x=>x.id===id);$('#customProduct').innerHTML=`<div class="custom-head"><div class="big-emoji">${p.emoji}</div><div><div class="eyebrow">Build your drink</div><h2>${JN.esc(p.name)}</h2><p>Start at ${JN.money(discounted(p))}</p></div></div>`;$('#customProductId').value=id;$('#customizeModal').showModal();}
function addCustomized(){const id=$('#customProductId').value,p=products.find(x=>x.id===id),qty=Number($('#qty').value)||1,size=$('#size').value,sugar=$('#sugar').value,ice=$('#ice').value,addons=$$('input[name=addon]:checked').map(x=>x.value);cart.push({key:crypto.randomUUID(),productId:id,name:p.name,emoji:p.emoji,qty,size,sugar,ice,addons,base:discounted(p)});saveCart();$('#customizeModal').close();JN.toast(`${p.name} added to cart`);}
function itemUnit(it){let u=it.base+(it.size==='Large'?20:it.size==='Jumbo'?35:0);if(it.addons.includes('Chia seeds'))u+=10;if(it.addons.includes('Mint boost'))u+=5;if(it.addons.includes('Protein scoop'))u+=25;return u;}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0);$$('[data-cart-count]').forEach(x=>x.textContent=count);$('#cartItems').innerHTML=cart.map(it=>`<div class="cart-item"><div class="cart-emoji">${it.emoji}</div><div class="grow"><strong>${JN.esc(it.name)}</strong><small>${it.size} · ${it.sugar} sugar · ${it.ice} ice</small>${it.addons.length?`<small>+ ${it.addons.map(JN.esc).join(', ')}</small>`:''}<div class="qty-row"><button data-minus="${it.key}">−</button><span>${it.qty}</span><button data-plus="${it.key}">+</button><button class="link danger" data-remove="${it.key}">Remove</button></div></div><b>${JN.money(itemUnit(it)*it.qty)}</b></div>`).join('')||'<div class="empty slim">Your cart is waiting for something fresh 🍊</div>';const total=cart.reduce((a,it)=>a+itemUnit(it)*it.qty,0);$('#cartTotal').textContent=JN.money(total);$('#checkoutBtn').disabled=!cart.length;$$('[data-plus]').forEach(b=>b.onclick=()=>{const i=cart.find(x=>x.key===b.dataset.plus);if(i&&i.qty<10)i.qty++;saveCart()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const i=cart.find(x=>x.key===b.dataset.minus);if(i&&i.qty>1)i.qty--;saveCart()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.remove);saveCart()});}

function setCustomerType(type){
  const isTeacher=type==='TEACHER';
  $('#customerType').value=isTeacher?'TEACHER':'STUDENT';
  $$('[data-order-type]').forEach(b=>b.classList.toggle('active',b.dataset.orderType===(isTeacher?'TEACHER':'STUDENT')));
  const roll=$('#rollField'), rollInput=roll.querySelector('input');
  roll.hidden=isTeacher; rollInput.required=!isTeacher; if(isTeacher) rollInput.value='';
  $('#nameLabel').textContent=isTeacher?'Teacher name':'Student name';
  const nameInput=$('#nameField input'); nameInput.placeholder=isTeacher?'Faculty name':'Your full name';
  $('#classLabel').textContent=isTeacher?'Department':'Class / Department';
  const classInput=$('#classField input'); classInput.placeholder=isTeacher?'e.g. Computer Science':'e.g. III B.Sc Computer Science';
  $('#roomLabel').textContent=isTeacher?'Staff room / Room no.':'Class / Room no.';
  const roomInput=$('#roomField input'); roomInput.placeholder=isTeacher?'e.g. Staff Room 2 / 204':'e.g. 204';
}

function toggleCart(open=true){$('#cartDrawer').classList.toggle('open',open);$('#scrim').classList.toggle('show',open)}
async function placeOrder(e){e.preventDefault();const fd=new FormData(e.target);const payload=Object.fromEntries(fd.entries());payload.items=cart.map(({productId,qty,size,sugar,ice,addons})=>({productId,qty,size,sugar,ice,addons}));try{const d=await JN.api('/api/orders',{method:'POST',body:JSON.stringify(payload)});cart=[];saveCart();$('#checkoutModal').close();toggleCart(false);showSuccess(d.order);loadProducts();}catch(err){JN.toast(err.message,'bad')}}
function showSuccess(o){$('#successBody').innerHTML=`<div class="success-icon">✓</div><div class="eyebrow">Order confirmed</div><h2>${o.id}</h2><p>${JN.esc(o.name)}, your fresh order is queued for <b>${JN.esc(o.timeSlot)}</b>.</p><div class="code-card"><span>Delivery verification code</span><strong>${o.pickupCode}</strong><small>Share only when you receive the order.</small></div><div class="receipt-row"><span>Total</span><b>${JN.money(o.total)}</b></div><div class="receipt-row"><span>Rewards earned</span><b>+${o.rewardPoints} pts</b></div><button class="btn wide" onclick="document.querySelector('#successModal').close();document.querySelector('#trackId').value='${o.id}';trackOrder()">Track order</button>`;$('#successModal').showModal();}
async function trackOrder(){const id=$('#trackId').value.trim(),roll=$('#trackRoll').value.trim();if(!id&&!roll)return JN.toast('Enter order ID or roll number','bad');try{const d=await JN.api(`/api/orders/track?id=${encodeURIComponent(id)}&rollNumber=${encodeURIComponent(roll)}`);$('#trackResults').innerHTML=d.orders.map(o=>orderTrackCard(o)).join('')||'<div class="empty slim">No matching order found.</div>';}catch(e){JN.toast(e.message,'bad')}}
function orderTrackCard(o){const steps=['PLACED','ACCEPTED','PREPARING','READY','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED'];const ix=steps.indexOf(o.status);return `<article class="track-card"><div class="track-top"><div><span class="status-pill ${o.status.toLowerCase()}">${JN.statusLabel(o.status)}</span><h3>${o.id}</h3><p>${JN.esc(o.block)} · ${JN.esc(o.classNumber)} · ${JN.esc(o.timeSlot)}</p></div><div class="track-price">${JN.money(o.total)}</div></div><div class="stepper">${steps.map((s,i)=>`<div class="step ${i<=ix?'done':''}"><i></i><span>${JN.statusLabel(s)}</span></div>`).join('')}</div>${o.status!=='DELIVERED'?`<div class="code-inline">Your delivery code: <b>${o.pickupCode}</b></div>`:''}<button class="link" data-reorder='${encodeURIComponent(JSON.stringify(o.items))}'>Quick reorder</button></article>`;}
function quickReorder(encoded){const items=JSON.parse(decodeURIComponent(encoded));for(const it of items){const p=products.find(x=>x.id===it.productId);if(p)cart.push({key:crypto.randomUUID(),productId:p.id,name:p.name,emoji:p.emoji,qty:it.qty,size:it.size,sugar:it.sugar,ice:it.ice,addons:it.addons||[],base:discounted(p)});}saveCart();toggleCart(true);JN.toast('Previous order added to cart');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-reorder]');if(b)quickReorder(b.dataset.reorder)});
document.addEventListener('DOMContentLoaded',()=>{$('#search').addEventListener('input',renderProducts);$('#cartOpen').onclick=()=>toggleCart(true);$('#cartClose').onclick=()=>toggleCart(false);$('#scrim').onclick=()=>toggleCart(false);$('#customAdd').onclick=addCustomized;$('#checkoutBtn').onclick=()=>{$('#checkoutModal').showModal();toggleCart(false)};$$('[data-order-type]').forEach(b=>b.onclick=()=>setCustomerType(b.dataset.orderType));setCustomerType('STUDENT');$('#checkoutForm').onsubmit=placeOrder;$('#trackBtn').onclick=trackOrder;$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());navigator.serviceWorker?.register('/sw.js').catch(()=>{});loadProducts();});
